# coding=utf-8

from kataja.singletons import ctrl, prefs, running_environment
from kataja.KatajaAction import KatajaAction


# ==== Class variables for KatajaActions:
#
# k_action_uid : unique id for calling this action. required, other are optional
# k_command : text used for menu command and log feedback, unless the method returns a fdback string
# k_tooltip : tooltip text for ui element. If not given, uses k_command as tooltip.
# k_undoable : is the action undoable, default is True
# k_shortcut : keyboard shortcut given as string, e.g. 'Ctrl+x'
# k_shortcut_context : can be nothing or 'parent_and_children' if shortcut is active only when the
#                      parent widget is visible and active
# k_dynamic : if True, there are many instances of this action with different ids, generated by
#             code, e.g. visualisation1...9
# k_checkable : should the action be checkable, default False
# k_exclusive : use together with k_dynamic, only one of the instances can be checked at time.
#
# ==== Methods:
#
# method : gets called when action is triggered. If it returns a string, this is used as a command
#          feedback string, otherwise k_command is printed to log.
# getter : if there is an UI element that can show state or display value, this method returns the
#          value. These are called quite often, but with values that have to change e.g. when item
#          is dragged, you'll have to update manually.
# enabler : if enabler is defined, the action is active (also reflected into its UI elements) only
#           when enabler returns True
#


class SwitchEditMode(KatajaAction):
    k_action_uid = 'switch_edit_mode'
    k_command = 'Toggle edit mode'
    k_shortcut = 'Ctrl+Shift+Space'
    k_undoable = False

    k_tooltip = 'Switch between free editing and derivation-based visualisation (%s+Shift+Space)' % \
                running_environment.cmd_or_ctrl

    def method(self, free_edit=None):
        """ Switch between visualisation mode and free edit mode
        :type free_edit: None to toggle between modes, True for free_drawing_mode,
        False for visualization
        :param state: triggering button or menu item state
        :return:
        """
        if free_edit is None:
            ctrl.free_drawing_mode = not ctrl.free_drawing_mode
        else:
            ctrl.free_drawing_mode = free_edit
        ctrl.ui.update_edit_mode()
        if ctrl.free_drawing_mode:
            return 'Free drawing mode: draw as you will, but there is no access to derivation ' \
                   'history for the structure.'
        else:
            return 'Derivation mode: you can edit the visualisation and browse the derivation ' \
                   'history, but the underlying structure cannot be changed.'

    def getter(self):
        return not ctrl.free_drawing_mode


class NextForest(KatajaAction):
    k_action_uid = 'next_forest'
    k_command = 'Next forest'
    k_shortcut = '.'
    k_undoable = False
    k_tooltip = 'Switch to next forest'

    def method(self):
        """ Show the next 'slide', aka Forest from a list in KatajaDocument.
        :return: None
        """
        i, forest = ctrl.main.forest_keeper.next_forest()
        ctrl.main.change_forest()
        return 'Next forest (.): %s: %s' % (i + 1, forest.textual_form())


class PreviousForest(KatajaAction):
    k_action_uid = 'previous_forest'
    k_command = 'Previous forest'
    k_shortcut = ','
    k_undoable = False
    k_tooltip = 'Switch to previous forest'

    def method(self):
        """ Show the previous 'slide', aka Forest from a list in KatajaDocument.
        :return: None
        """
        i, forest = ctrl.main.forest_keeper.prev_forest()
        ctrl.main.change_forest()
        return 'Previous forest (,): %s: %s' % (i + 1, forest.textual_form())


class NextStep(KatajaAction):
    k_action_uid = 'next_derivation_step'
    k_command = 'Next derivation step'
    k_shortcut = '>'
    k_undoable = False
    k_tooltip = 'Move to next frame in animation / derivation'

    def method(self):
        """ User action "step forward (>)", Move to next derivation step """
        ctrl.forest.derivation_steps.next_derivation_step()


class PreviousStep(KatajaAction):
    k_action_uid = 'prev_derivation_step'
    k_command = 'Previous derivation step'
    k_shortcut = '<'
    k_undoable = False
    k_tooltip = 'Move to previous frame in animation / derivation'

    def method(self):
        """ User action "step backward (<)" , Move backward in derivation steps """
        ctrl.forest.derivation_steps.previous_derivation_step()


